dark-mode: true
show-model-warnings: false
analytics-disable: true
openai-api-key: not-needed
openai-api-base: http://localhost:4141/
# model: gemini/gemini-2.5-pro-preview-05-06
# model: gemini/gemini-2.5-flash-preview-04-17
# model: openai/gemini-2.5-pro-preview-06-05
# model: openai/gemini-2.5-flash
# model: openai/claude-3.7-sonnet-thought
# model: openai/claude-3.7-sonnet
# model: openai/claude-3.5-sonnet
model: claude-sonnet-4
# model: claude-opus-4
# model: openai/gpt-4o
# model: openai/o1
# model: openai/o3-mini
alias:
  - "sonnet:openai/claude-sonnet-4"
  - "sonnet-thinking:openai/claude-3.7-sonnet-thought"
  - "gemini-flash:gemini/gemini-2.5-flash-preview-04-17"
  - "gemini:gemini-2.5-pro-preview-06-05"

## Specify the model to use for commit messages and chat history summarization (default depends on --model)
weak-model: gemini/gemini-2.5-flash-preview-04-17
# weak-model: gemini/gemini-2.0-flash
# weak-model: openai/gpt-4o-mini
# weak-model: openai/gpt-4o

## Specify the model to use for editor tasks (default depends on --model)
# editor-model: openai/claude-3.7-sonnet-thought
# editor-model: openai/claude-3.7-sonnet
# editor-model: openai/claude-3.5-sonnet
# editor-model: gemini/gemini-2.0-flash

###############
# Git settings:

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false

## Enable/disable commits when repo is found dirty (default: True)
dirty-commits: false

## Attribute aider code changes in the git author name (default: True)
attribute-author: false

## Attribute aider commits in the git committer name (default: True)
attribute-committer: false
