#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     platform=linux;;
  Darwin*)    platform=mac;;
  CYGWIN*)    platform=cygwin;;
  MINGW*)     platform=mingw;;
  *)          platform="UNKNOWN:${unameOut}"
esac

if [ "$platform" == "mac" ]; then
  echo "Detected MacOS"
  if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  brew install \
    node \
    nomad \
    pnpm \
    rustup \
    vim \
    wezterm \
    zoxide \
    ;
  if command -v rustup &> /dev/null; then
    rustup component add rust-src
  fi
  if ! command -v dotter &> /dev/null; then
    cargo install dotter
  fi

fi
