[bootstrap.packages]
"apt:age" = "latest"
"pacman:age" = "latest"

"apt:fish" = "latest"
"pacman:fish" = "latest"

"apt:zoxide" = "latest"
"pacman:zoxide" = "latest"

[bootstrap.user]
login_shell = "/usr/bin/fish"
