[bootstrap.packages]
"brew:age" = "latest"
"brew:bat" = "latest"
"brew:ca-certificates" = "latest"
"brew:cargo-cache" = "latest"
"brew:cargo-make" = "latest"
"brew:cargo-watch" = "latest"
"brew-cask:copilot-cli" = "latest"
"brew:ddgr" = "latest"
"brew:docker" = "latest"
"brew:docker-compose" = "latest"
"brew:docker-credential-helper" = "latest"
"brew:efm-langserver" = "latest"
"brew:ffmpeg" = "latest"
"brew:fish" = "latest"
"brew:lazydocker" = "latest"
"brew-cask:radix" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"
