[aichat.files]
".config/aichat" = { type = "symbolic" , target = "~/.config/aichat" }

# [aider.files]
# ".aider.conf.yml" = { type = "symbolic" , target = "~/.aider.conf.yml" }
# ".aider.model.metadata.json" = { type = "symbolic" , target = "~/.aider.model.metadata.json" }

[awesomewm.files]
".config/awesome" = { type = "symbolic" , target = "~/.config/awesome" }

[bash.files]
".bash_profile" = { type = "symbolic", target = "~/.bash_profile" }

[bspwm.files]
".config/bspwm" = { type = "symbolic" , target = "~/.config/bspwm" }

[efm-langserver.files]
".config/efm-langserver" = { type = "symbolic" , target = "~/.config/efm-langserver" }

[fish.files]
".config/fish" = { type = "symbolic", target = "~/.config/fish" }

[git.files]
".gitconfig" = "~/.gitconfig"

[ghostty.files]
".config/ghostty" = { type = "symbolic" , target = "~/.config/ghostty" }

[mise.files]
".config/mise" = { type = "symbolic" , target = "~/.config/mise" }

[nvim.files]
".config/nvim/init.vim" = { type = "symbolic" , target = "~/.config/nvim/init.vim" }

[picom.files]
".config/picom" = { type = "symbolic" , target = "~/.config/picom" }

[polybar.files]
".config/polybar" = { type = "symbolic" , target = "~/.config/polybar" }

[rofi.files]
".config/rofi" = { type = "symbolic" , target = "~/.config/rofi" }

[sxhkd.files]
".config/sxhkd" = { type = "symbolic" , target = "~/.config/sxhkd" }

[xorg.files]
".xprofile" = { type = "symbolic" , target = "~/.xprofile" }

[television.files]
".config/television" = { type = "symbolic" , target = "~/.config/television" }

[tmux.files]
".tmux.conf" = { type = "symbolic" , target = "~/.tmux.conf" }

[vim.files]
".vimrc" = { type = "symbolic" , target = "~/.vimrc" }

[wezterm.files]
".config/wezterm" = { type = "symbolic" , target = "~/.config/wezterm" }

[zed.files]
".config/zed" = { type = "symbolic" , target = "~/.config/zed" }

[zsh.files]
".zshrc" = { type = "symbolic" , target = "~/.zshrc" }
