[helpers]

[default]
depends = [
  "cargo",
]

[default.files]
".bash_profile" = { type = "symbolic", target = "~/.bash_profile" }
".vimrc" = { type = "symbolic" , target = "~/.vimrc" }

[default.variables]

[cargo.files]
".cargo/config" = "~/.cargo/config"
