includes = []
packages = [
  "awesomewm",
  "bash",
  "bspwm",
  "efm-langserver",
  "git",
  "nvim",
  "picom",
  "polybar",
  "rofi",
  "sxhkd",
  "xorg",
  "tmux",
  "vim",
  "wezterm",
  "zed",
  "zsh"
]
